"""add registrations to livesync

Revision ID: 86fd11a6cab4
Revises: ff1323696f67
Create Date: 2023-03-06 15:20:02.568517
"""

from alembic import op


# revision identifiers, used by Alembic.
revision = '86fd11a6cab4'
down_revision = 'ff1323696f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        alter table plugin_livesync.queues add column registration_id integer;
        create index ix_queues_registration_id on plugin_livesync.queues using btree (registration_id);
        alter table plugin_livesync.queues add constraint ck_queues_valid_registration_entry check (type <> 8 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND registration_id IS NOT NULL);
        alter table plugin_livesync.queues add constraint fk_queues_registration_id_event_registrations foreign key (registration_id) references event_registration.registrations(id);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_enum_change;
        alter table plugin_livesync.queues add constraint ck_queues_valid_enum_change CHECK (change = ANY (ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9]));

        alter table plugin_livesync.queues drop constraint ck_queues_valid_enum_type;
        alter table plugin_livesync.queues add constraint ck_queues_valid_enum_type CHECK (type = ANY (ARRAY[1, 2, 3, 4, 5, 6, 7, 8]));

        alter table plugin_livesync.queues drop constraint ck_queues_valid_attachment_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_attachment_entry CHECK (type <> 7 OR category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND registration_id IS NULL AND attachment_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_category_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_category_entry CHECK (type <> 1 OR attachment_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND registration_id IS NULL AND category_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_contribution_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_contribution_entry CHECK (type <> 3 OR attachment_id IS NULL AND category_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND registration_id IS NULL AND contribution_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_event_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_event_entry CHECK (type <> 2 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND registration_id IS NULL AND event_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_note_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_note_entry CHECK (type <> 6 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND registration_id IS NULL AND note_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_session_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_session_entry CHECK (type <> 5 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND subcontribution_id IS NULL AND registration_id IS NULL AND session_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_subcontribution_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_subcontribution_entry CHECK (type <> 4 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND registration_id IS NULL AND subcontribution_id IS NOT NULL);

    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        alter table plugin_livesync.queues drop column registration_id;
        alter table plugin_livesync.queues drop constraint ck_queues_valid_registration_entry;

        alter table plugin_livesync.queues drop constraint ck_queues_valid_enum_change;
        alter table plugin_livesync.queues add constraint ck_queues_valid_enum_change CHECK (change = ANY (ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9]));

        alter table plugin_livesync.queues drop constraint ck_queues_valid_enum_type;
        alter table plugin_livesync.queues add constraint ck_queues_valid_enum_type CHECK (type = ANY (ARRAY[1, 2, 3, 4, 5, 6, 7]));


        alter table plugin_livesync.queues drop constraint ck_queues_valid_attachment_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_attachment_entry CHECK (type <> 7 OR category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND attachment_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_category_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_category_entry CHECK (type <> 1 OR attachment_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND category_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_contribution_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_contribution_entry CHECK (type <> 3 OR attachment_id IS NULL AND category_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND contribution_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_event_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_event_entry CHECK (type <> 2 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND event_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_note_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_note_entry CHECK (type <> 6 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND session_id IS NULL AND subcontribution_id IS NULL AND note_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_session_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_session_entry CHECK (type <> 5 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND subcontribution_id IS NULL AND session_id IS NOT NULL);

        alter table plugin_livesync.queues drop constraint ck_queues_valid_subcontribution_entry;
        alter table plugin_livesync.queues add  constraint ck_queues_valid_subcontribution_entry CHECK (type <> 4 OR attachment_id IS NULL AND category_id IS NULL AND contribution_id IS NULL AND event_id IS NULL AND note_id IS NULL AND session_id IS NULL AND subcontribution_id IS NOT NULL);

    ''')
    # ### end Alembic commands ###
