[pytest]
; more verbose summary (include skip/fail/error/warning)
addopts = -rsfEw
; only check for tests in suffixed files
python_files = *_test.py
; we need the ror plugin to be loaded
indico_plugins = ror
