"""Add affiliations vector store.

Revision ID: f95cb312d2bb
Revises:
Create Date: 2026-03-13 12:43:32.863241
"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.sql.ddl import CreateSchema, DropSchema


# revision identifiers, used by Alembic.
revision = 'f95cb312d2bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSchema('plugin_ror'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=512), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_id'], ['indico.affiliations.id'], name=op.f('fk_affiliation_documents_affiliation_id_affiliations'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_affiliation_documents')),
    schema='plugin_ror'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliation_documents', schema='plugin_ror')
    # ### end Alembic commands ###
    op.execute(DropSchema('plugin_ror'))
