"""create table

Revision ID: d86e85a383c1
Revises: b79318836818
Create Date: 2020-04-03 19:57:35.771416
"""

import sqlalchemy as sa
from alembic import op



# revision identifiers, used by Alembic.
revision = 'd86e85a383c1'
down_revision = 'b79318836818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_meetings',
    sa.Column('vc_room_id', sa.Integer(), nullable=False),
    sa.Column('meeting', sa.BigInteger(), nullable=True),
    sa.Column('url_zoom', sa.Text(), nullable=False),
    sa.Column('owned_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owned_by_id'], [u'users.users.id'], name=op.f('fk_zoom_meetings_owned_by_id_users')),
    sa.ForeignKeyConstraint(['vc_room_id'], [u'events.vc_rooms.id'], name=op.f('fk_zoom_meetings_vc_room_id_vc_rooms')),
    sa.PrimaryKeyConstraint('vc_room_id', name=op.f('pk_zoom_meetings')),
    schema='plugin_vc_zoom'
    )
    op.create_index(op.f('ix_zoom_meetings_meeting'), 'zoom_meetings', ['meeting'], unique=False, schema='plugin_vc_zoom')
    op.create_index(op.f('ix_zoom_meetings_owned_by_id'), 'zoom_meetings', ['owned_by_id'], unique=False, schema='plugin_vc_zoom')
    op.create_index(op.f('ix_zoom_meetings_url_zoom'), 'zoom_meetings', ['url_zoom'], unique=False, schema='plugin_vc_zoom')
    op.drop_index('ix_zoom_extensions_url_zoom', table_name='zoom_extensions', schema='plugin_vc_zoom')
    op.drop_table('zoom_extensions', schema='plugin_vc_zoom')
    op.drop_index('ix_uq_zoom_licenses_license_id', table_name='zoom_licenses', schema='plugin_vc_zoom')
    op.drop_index('ix_zoom_licenses_license_name', table_name='zoom_licenses', schema='plugin_vc_zoom')
    op.drop_table('zoom_licenses', schema='plugin_vc_zoom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_licenses',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('plugin_vc_zoom.zoom_licenses_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('license_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('license_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'pk_zoom_licenses'),
    schema='plugin_vc_zoom'
    )
    op.create_index('ix_zoom_licenses_license_name', 'zoom_licenses', ['license_name'], unique=False, schema='plugin_vc_zoom')
    op.create_index('ix_uq_zoom_licenses_license_id', 'zoom_licenses', ['license_id'], unique=True, schema='plugin_vc_zoom')
    op.create_table('zoom_extensions',
    sa.Column('vc_room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url_zoom', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vc_room_id'], [u'events.vc_rooms.id'], name=u'fk_zoom_extensions_vc_room_id_vc_rooms'),
    sa.PrimaryKeyConstraint('vc_room_id', name=u'pk_zoom_extensions'),
    schema='plugin_vc_zoom'
    )
    op.create_index('ix_zoom_extensions_url_zoom', 'zoom_extensions', ['url_zoom'], unique=False, schema='plugin_vc_zoom')
    op.drop_index(op.f('ix_zoom_meetings_url_zoom'), table_name='zoom_meetings', schema='plugin_vc_zoom')
    op.drop_index(op.f('ix_zoom_meetings_owned_by_id'), table_name='zoom_meetings', schema='plugin_vc_zoom')
    op.drop_index(op.f('ix_zoom_meetings_meeting'), table_name='zoom_meetings', schema='plugin_vc_zoom')
    op.drop_table('zoom_meetings', schema='plugin_vc_zoom')
    # ### end Alembic commands ###
