"""create table

Revision ID: d54585a383v1
Revises: b79318836818
Create Date: 2020-04-05 15:39:35.771416
"""

import sqlalchemy as sa
from alembic import op

from sqlalchemy.sql.ddl import CreateSchema, DropSchema

# revision identifiers, used by Alembic.
revision = 'd54585a383v1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSchema('plugin_vc_zoom'))
    op.create_table('zoom_meetings',
    sa.Column('vc_room_id', sa.Integer(), nullable=False),
    sa.Column('meeting', sa.BigInteger(), nullable=True),
    sa.Column('url_zoom', sa.Text(), nullable=False),
    sa.Column('owned_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owned_by_id'], [u'users.users.id'], name=op.f('fk_zoom_meetings_owned_by_id_users')),
    sa.ForeignKeyConstraint(['vc_room_id'], [u'events.vc_rooms.id'], name=op.f('fk_zoom_meetings_vc_room_id_vc_rooms')),
    sa.PrimaryKeyConstraint('vc_room_id', name=op.f('pk_zoom_meetings')),
    schema='plugin_vc_zoom'
    )
    op.create_index(op.f('ix_zoom_meetings_meeting'), 'zoom_meetings', ['meeting'], unique=False, schema='plugin_vc_zoom')
    op.create_index(op.f('ix_zoom_meetings_owned_by_id'), 'zoom_meetings', ['owned_by_id'], unique=False, schema='plugin_vc_zoom')
    op.create_index(op.f('ix_zoom_meetings_url_zoom'), 'zoom_meetings', ['url_zoom'], unique=False, schema='plugin_vc_zoom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoom_meetings_url_zoom'), table_name='zoom_meetings', schema='plugin_vc_zoom')
    op.drop_index(op.f('ix_zoom_meetings_owned_by_id'), table_name='zoom_meetings', schema='plugin_vc_zoom')
    op.drop_index(op.f('ix_zoom_meetings_meeting'), table_name='zoom_meetings', schema='plugin_vc_zoom')
    op.drop_table('zoom_meetings', schema='plugin_vc_zoom')
    op.execute(DropSchema('plugin_vc_zoom'))
    # ### end Alembic commands ###
