"""crea tabella

Revision ID: b79318836818
Revises: 
Create Date: 2020-03-12 10:30:09.256157
"""

import sqlalchemy as sa
from alembic import op

from sqlalchemy.sql.ddl import CreateSchema, DropSchema


# revision identifiers, used by Alembic.
revision = 'b79318836818'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute(CreateSchema('plugin_vc_zoom'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_extensions',
    sa.Column('vc_room_id', sa.Integer(), nullable=False),
    sa.Column('url_zoom', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['vc_room_id'], [u'events.vc_rooms.id'], name=op.f('fk_zoom_extensions_vc_room_id_vc_rooms')),
    sa.PrimaryKeyConstraint('vc_room_id', name=op.f('pk_zoom_extensions')),
    schema='plugin_vc_zoom'
    )
    op.create_index(op.f('ix_zoom_extensions_url_zoom'), 'zoom_extensions', ['url_zoom'], unique=False, schema='plugin_vc_zoom')
    op.create_table('zoom_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_id', sa.Text(), nullable=False),
    sa.Column('license_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zoom_licenses')),
    schema='plugin_vc_zoom'
    )
    op.create_index(op.f('ix_uq_zoom_licenses_license_id'), 'zoom_licenses', ['license_id'], unique=True, schema='plugin_vc_zoom')
    op.create_index(op.f('ix_zoom_licenses_license_name'), 'zoom_licenses', ['license_name'], unique=False, schema='plugin_vc_zoom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zoom_licenses_license_name'), table_name='zoom_licenses', schema='plugin_vc_zoom')
    op.drop_index(op.f('ix_uq_zoom_licenses_license_id'), table_name='zoom_licenses', schema='plugin_vc_zoom')
    op.drop_table('zoom_licenses', schema='plugin_vc_zoom')
    op.drop_index(op.f('ix_zoom_extensions_url_zoom'), table_name='zoom_extensions', schema='plugin_vc_zoom')
    op.drop_table('zoom_extensions', schema='plugin_vc_zoom')
    # ### end Alembic commands ###
    op.execute(DropSchema('plugin_vc_zoom'))
